import React,{useState} from 'react';
type Row=Record<string,any>;
const fmt=(n:number|null)=>n===null?'—':n.toLocaleString('en-IN',{maximumFractionDigits:1});
const label=(s:string)=>s.replaceAll('_',' ');
export function latest(rows:Row[]){const map=new Map<string,Row>();for(const r of rows){const key=[r.scope,r.content_id||r.target_url||'account',r.metric,r.window].join('|');if(!map.has(key)||map.get(key)!.observed_at<r.observed_at)map.set(key,r)}return [...map.values()]}
export default function Insights({data}:{data:Row|null}){
 const [tab,setTab]=useState('Overview'),[period,setPeriod]=useState('90'),[metric,setMetric]=useState('impressions'),[window,setWindow]=useState(''),[format,setFormat]=useState(''),[search,setSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 if(!data)return <section className="empty">Loading performance evidence…</section>;
 const all=latest(data.metrics), daily=all.filter(r=>r.scope==='account'&&r.window.startsWith('day:')).map((r):Row=>({...r,day:r.window.slice(4)}));
 const end=daily.map(r=>r.day).sort().at(-1)||'', start=end?new Date(new Date(end+'T00:00:00Z').getTime()-(Number(period)-1)*86400000).toISOString().slice(0,10):'';
 const lo=period==='custom'?from:period==='all'?'':start,hi=period==='custom'?to:end;
 const selected=daily.filter(r=>(!lo||r.day>=lo)&&(!hi||r.day<=hi));
 const measured=(r:Row)=>r.availability==='measured'&&typeof r.value==='number'&&Number.isFinite(r.value);
 const values=(m:string)=>selected.filter(r=>r.metric===m&&measured(r));
 const total=(m:string)=>values(m).length?values(m).reduce((n,r)=>n+r.value,0):null;
 const series=values(metric).sort((a,b)=>a.day.localeCompare(b.day)),max=Math.max(1,...series.map(r=>r.value));
 const post=all.filter(r=>r.scope==='post'),windows=[...new Set(post.map(r=>r.window))].sort(),win=windows.includes(window)?window:windows[0]||'';
 const rows=post.filter(r=>r.metric===metric&&r.window===win&&(!format||(r.format||'unknown')===format)&&(!search||`${r.title||''} ${r.target_url||''}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>(measured(b)?b.value:-Infinity)-(measured(a)?a.value:-Infinity));
 const formats=[...new Set(post.map(r=>r.format||'unknown'))], assetGroups=[...new Set(data.assets.map((r:Row)=>r.format))] as string[];
 const peak=series.reduce((a:Row|null,r:Row)=>!a||r.value>a.value?r:a,null);
 const observed=all.map(r=>r.observed_at).sort().at(-1);
 return <div className="insights-dashboard">
 <section className="insight-heading"><div><span className="eyebrow">THE PERFORMANCE STUDIO</span><h2>Find what earns attention.</h2><p>Explore your reach, the conversations it creates, and the assets behind your posts.</p></div><div className="source-stamp">Saved observations<small>Latest capture {observed?.slice(0,10)||'unavailable'} · no live API refresh</small></div></section>
 <div className="insight-tabs" role="tablist" aria-label="Insights view">{['Overview','Post performance','Assets'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>{setTab(t);setFormat('');setSearch('');if(t==='Post performance'&&metric==='followers_gained')setMetric('impressions')}}>{t}</button>)}</div>
 {tab==='Overview'&&<>
 <div className="insight-filters"><label>Reporting period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="30">Last 30 recorded days</option><option value="90">Last 90 recorded days</option><option value="all">All recorded days</option><option value="custom">Custom range</option></select></label>{period==='custom'&&<><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<small>{lo||daily.map(r=>r.day).sort()[0]||'—'} → {hi||end||'—'}<br/>Based on activity dates in the export</small></div>
 {lo&&hi&&lo>hi&&<div role="alert" className="note">Choose an end date on or after the start date.</div>}
 <div className="stats">{[['impressions','Impressions'],['engagements','Engagements'],['followers_gained','Followers gained']].map(([m,t])=><div className="stat" key={m}><span>{t}</span><strong>{fmt(total(m))}</strong><small>{values(m).length} measured days · export definition</small></div>)}<div className="stat"><span>Engagements / impressions</span><strong>{total('impressions')&&total('engagements')!==null&&values('impressions').map(r=>r.day).sort().join()===values('engagements').map(r=>r.day).sort().join()?fmt(total('engagements')!/total('impressions')!*100)+'%':'—'}</strong><small>Only calculated with matching day coverage</small></div></div>
 <div className="insight-layout"><section className="panel"><div className="sectionhead"><div><span className="eyebrow">DAILY TREND</span><h2>Attention over time</h2></div><select aria-label="Trend metric" value={metric} onChange={e=>setMetric(e.target.value)}>{['impressions','engagements','followers_gained'].map(m=><option key={m}>{m}</option>)}</select></div>{series.length?<><div className="trend-chart" role="img" aria-label={`Daily ${label(metric)}, ${series.length} measured days. Highest ${peak?.value} on ${peak?.day}.`}><div className="chart-top">{fmt(max)}</div><div className="chart-bars">{series.map(r=><div key={r.day} className="chart-column" tabIndex={0} aria-label={`${r.day}: ${fmt(r.value)} ${label(metric)}`} style={{height:`${Math.max(.5,r.value/max*100)}%`}}><span>{r.day}<b>{fmt(r.value)} {label(metric)}</b></span></div>)}</div><div className="chart-axis"><span>{series[0].day}</span><span>{series.at(-1)?.day}</span></div></div><small>Each bar is an observed day. Missing days are omitted, not recorded as zero.</small></>:<div className="empty">No daily measurements in this range.</div>}</section><section className="panel insights-reading"><span className="eyebrow">READ THE SIGNAL</span><h2>What stands out</h2>{peak?<><strong>{fmt(peak.value)}</strong><p>Highest daily {label(metric)} in this selection, recorded on <b>{peak.day}</b>.</p><hr/><p>{series.length} days have measurements for this metric. A spike alone does not identify the post or action that caused it.</p></>:<p>Select a period with measured activity to see a signal.</p>}<button onClick={()=>{setTab('Post performance');setMetric('impressions')}}>Explore post performance →</button></section></div>
 <section className="panel experiments"><span className="eyebrow">LEARN, THEN ADJUST</span><h2>Your next experiments</h2>{data.experiments.length?data.experiments.map((e:Row)=><article key={e.id}><strong>{e.hypothesis}</strong><p>{e.variable} · {e.start_date} · {e.status}</p>{e.decision&&<p>{e.decision}</p>}</article>):<p>No experiment recorded yet. Run SMP REVIEW to turn these observations into the next content experiment.</p>}</section>
 </>}
 {tab==='Post performance'&&<>
 <div className="insight-filters"><label>Metric<select value={metric==='followers_gained'?'impressions':metric} onChange={e=>setMetric(e.target.value)}>{['impressions','engagements'].map(m=><option key={m}>{m}</option>)}</select></label><label>Measurement window<select value={win} onChange={e=>setWindow(e.target.value)}>{windows.map(w=><option key={w}>{w}</option>)}</select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="">All formats</option>{formats.map(f=><option key={f} value={f}>{label(f)}</option>)}</select></label><label>Find a post<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title or LinkedIn URL"/></label></div>
 <div className="insight-layout"><section className="panel"><span className="eyebrow">POST LEADERBOARD</span><h2>Strongest recorded results</h2><p>Ranked by {label(metric)} in the exact selected window. Top-post exports may cover only a subset of your posts.</p>{rows.length?rows.map((r,i)=><div className="rank-row" key={r.id}><span className="rank">{String(i+1).padStart(2,'0')}</span><div><a href={r.target_url?.startsWith('https://')?r.target_url:undefined} target="_blank" rel="noreferrer">{r.title||r.target_url?.split('/').filter(Boolean).at(-1)?.slice(0,85)||r.content_id||'Unlinked post'}</a><small>{r.format||'Format not linked'} · {r.observed_at.slice(0,10)}</small><meter min={0} max={Math.max(1,...rows.filter(measured).map(r=>r.value))} value={measured(r)?r.value:0}/></div><b>{measured(r)?fmt(r.value):'Unavailable'}</b></div>):<div className="empty">No matching post measurements.</div>}</section><section className="panel insights-reading"><span className="eyebrow">COMPARISON NOTES</span><h2>Keep the context</h2><strong>{rows.filter(measured).length}</strong><p>Posts with measured {label(metric)} in this view.</p><hr/><p>We retain the latest observation per post, metric and window. Cumulative snapshots are never added together.</p><p>Unknown formats stay unknown. Historical rankings do not establish which asset style performs best.</p></section></div>
 </>}
 {tab==='Assets'&&<><section className="panel"><div className="sectionhead"><div><span className="eyebrow">CREATIVE PERFORMANCE</span><h2>The assets behind the results</h2></div><label>Asset format <select value={format} onChange={e=>setFormat(e.target.value)}><option value="">All formats</option>{assetGroups.map(f=><option key={f}>{f}</option>)}</select></label></div><p>Performance is linked at post level, not attributed to an individual image or PDF page. Archived versions remain separate.</p><div className="insight-filters"><label>Compare metric<select value={metric==='followers_gained'?'impressions':metric} onChange={e=>setMetric(e.target.value)}><option>impressions</option><option>engagements</option></select></label><label>Exact performance window<select value={win} onChange={e=>setWindow(e.target.value)}>{windows.map(w=><option key={w}>{w}</option>)}</select></label></div><div className="asset-summary">{assetGroups.filter(f=>!format||format===f).map(f=>{const assets=data.assets.filter((a:Row)=>a.format===f);const ids=new Set(assets.map((a:Row)=>a.content_id));const linked=post.filter(r=>ids.has(r.content_id)&&measured(r)&&r.metric===(metric==='followers_gained'?'impressions':metric)&&r.window===win);return <article key={f}><span className="formatmark">{label(f)}</span><h3>{assets.filter((a:Row)=>a.active).length} active assets</h3><p>{ids.size} linked posts · {assets.filter((a:Row)=>!a.active).length} archived assets</p><strong>{new Set(linked.map(r=>r.content_id)).size} posts with measurements</strong><h3>{linked.length?fmt(linked.reduce((n,r)=>n+r.value,0)/linked.length):'—'} average {metric==='followers_gained'?'impressions':label(metric)} per measured post</h3><small>{linked.length?'Descriptive comparison only; formats have different topics and audiences.':'Performance unavailable until a measurement is linked to these posts.'}</small></article>})}</div></section><div className="assetgrid insights-assets">{data.assets.filter((a:Row)=>!format||a.format===format).map((a:Row)=><article className="assetcard" key={a.id}>{a.format==='image'?<img src={'/api/asset/'+a.id} alt={a.alt_text}/>:<div className="pdfcover">{a.format==='document'?'PDF':label(a.format)}<span>{a.active?'Active asset':'Archived version'}</span></div>}<strong>{a.title}</strong><small>{a.alt_text} · {a.active?'Active':'Archived'}</small><button onClick={()=>{setTab('Post performance');setFormat(a.format);setSearch(a.title);setMetric('impressions')}}>View linked performance →</button></article>)}</div>{!data.assets.length&&<div className="empty">No registered assets yet.</div>}</>}
 <details className="insight-provenance"><summary>Data coverage & methodology</summary><p>{data.metrics.length} stored observations; {all.length} after retaining the latest matching snapshot. Daily account metrics, exact-window post metrics and asset inventory use separate controls. Asset counts are inventory, not performance. Account export totals and daily totals are not added together. Personal-post API analytics access is not verified.</p><p>Sources: {[...new Set(data.metrics.map((r:Row)=>r.source))].join(' · ')}</p></details>
 </div>
}
