import React, {useState} from 'react';
type AppName = 'publish' | 'identity';
type FieldName = 'client_id' | 'client_secret' | 'redirect_uri';
type Values = Record<AppName, Record<FieldName, string>>;
const blank = ():Values => ({publish:{client_id:'',client_secret:'',redirect_uri:''},identity:{client_id:'',client_secret:'',redirect_uri:''}});
export default function LinkedInSettings({status,save}:{status:any,save:(body:unknown)=>Promise<any>}) {
 const [values,setValues]=useState<Values>(blank),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function persist(body:unknown){setBusy(true);setError('');setMessage('');try{await save(body);setValues(blank());setMessage('Settings saved privately in .env.local. Existing blank fields were kept. This does not authenticate LinkedIn.')}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <section className="linkedin-setup"><div className="note"><strong>Local configuration</strong><p>Store your own app credentials here. Empty fields keep existing values. Saved values are never returned to this page. OAuth sign-in, callback handling and API publishing are not implemented in this release; use the documented browser workflow. These app settings prepare a future API integration.</p><p>Follow <code>docs/linkedin-setup.md</code> in your repository for developer portal steps, products, scopes and redirect URI requirements.</p></div>
 {error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert" role="status">{message}</div>}
 <form onSubmit={e=>{e.preventDefault();persist(values)}}><div className="setupgrid">{(['publish','identity'] as AppName[]).map(app=><section className="panel" key={app}><span className="eyebrow">{app==='publish'?'PUBLISHING APP':'IDENTITY APP'}</span><h2>{app==='publish'?'Share on LinkedIn':'Sign In with LinkedIn'}</h2><p>{app==='publish'?'Product: Share on LinkedIn. Permission: w_member_social.':'Product: Sign In with LinkedIn using OpenID Connect. Permissions: openid, profile, email.'}</p><p className="setupstate">{String(status?.apps?.[app]?.status||'not_configured').replaceAll('_',' ')} · Authentication not established</p>
 {(['client_id','client_secret','redirect_uri'] as FieldName[]).map(field=><label key={field}>{({client_id:'Client ID',client_secret:'Client secret',redirect_uri:'Registered redirect URI'})[field]}<input autoComplete="off" type={field==='client_secret'?'password':'text'} spellCheck={false} value={values[app][field]} placeholder={status?.apps?.[app]?.fields_present?.[field]?'Saved · leave empty to keep':field==='redirect_uri'?'Exact URI from your implemented OAuth integration':'Not configured'} maxLength={2048} onChange={e=>setValues({...values,[app]:{...values[app],[field]:e.target.value}})}/></label>)}
 <button type="button" disabled={busy} onClick={()=>persist({[app]:{clear:true}})}>Clear this app's saved settings</button></section>)}</div><div className="buttons"><button className="primary" disabled={busy} type="submit">{busy?'Saving…':'Save LinkedIn settings'}</button><a href="https://www.linkedin.com/developers/apps" target="_blank" rel="noreferrer">Open LinkedIn Developer portal ↗</a></div></form></section>
}
