import React, {useEffect, useState, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import Insights from './Insights';
import LinkedInSettings from './LinkedInSettings';
type Row = Record<string, any>;
let token='';
let displayTimezone='UTC';
async function api(path:string, body?:unknown) {
 const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-SMP-Token':token},body:JSON.stringify(body)});
 const d=await r.json(); if(!r.ok)throw new Error(d.error||'Request failed'); return d;
}
const names:Record<string,string>={START:'Start workspace',STATUS:'Check status',WEEK:'Prepare week',SCHEDULE:'Schedule batch',ENGAGE:'Engage', 'ENGAGE+':'Engage+',NETWORK:'Your network',DISCOVER:'Discover people',RECRUITERS:'Recruiter discussions','RECRUITER+':'Hiring outreach',REPLIES:'Reply to conversations',REVIEW:'Review performance',REWORK:'Rework drafts',ASSET:'Create asset',IMPORT:'Import export','EIGHT-WEEK':'Pilot review',BACKUP:'Back up workspace',END:'Save handover'};
const pages=['Home','Actions','Content','Assets','Engagement','Network','Opportunities','Insights','Runs','LinkedIn setup'];
const date=(v:any)=>v?new Date(v).toLocaleString(undefined,{timeZone:displayTimezone,dateStyle:'medium',timeStyle:'short'}):'Not recorded';
const label=(v:any)=>String(v??'Unavailable').replaceAll('_',' ');
function Badge({value}:{value:any}) {return <span className={'badge '+String(value)}>{label(value)}</span>}
function Link({url,children}:{url:any,children:React.ReactNode}) {return typeof url==='string'&&url.startsWith('https://')?<a href={url} target="_blank" rel="noreferrer">{children} ↗</a>:<span>{children}</span>}
function App(){
 const submission=useRef<string|undefined>(undefined), submitting=useRef(false);
 const [page,setPage]=useState('Home'),[overview,setOverview]=useState<Row|null>(null),[commands,setCommands]=useState<Row>({}),[data,setData]=useState<Row>({rows:[],total:0,page:1}),[query,setQuery]=useState(''),[num,setNum]=useState(1),[membership,setMembership]=useState(''),[bucket,setBucket]=useState(''),[metricScope,setMetricScope]=useState(''),[insights,setInsights]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState<Row|null>(null),[action,setAction]=useState(''),[params,setParams]=useState<Row>({}),[batch,setBatch]=useState<Row|null>(null),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!action&&!detail)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector('[role=dialog]') as HTMLElement|null;const items=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea')||[]);items()[0]?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAction('');setDetail(null)}if(e.key==='Tab'){const list=items();if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus()}},[Boolean(action),Boolean(detail)]);
 useEffect(()=>{submission.current=undefined},[action,params,batch]);
 async function load(){try{const next=await api('overview');displayTimezone=next.workspace?.timezone||'UTC';setOverview(next);}catch(e){setError(String(e))}}
 useEffect(()=>{api('session').then(x=>{token=x.token;return api('commands')}).then(x=>setCommands(x.commands)).catch(e=>setError(String(e)));load();const t=setInterval(()=>{load();setRefresh(x=>x+1)},10000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(['Home','Actions','Insights','LinkedIn setup'].includes(page))return; let live=true;api(`list/${page.toLowerCase()}?page=${num}&q=${encodeURIComponent(query)}&membership=${membership}&bucket=${encodeURIComponent(bucket)}&scope=${metricScope}`).then(x=>{if(live)setData(x)}).catch(e=>setError(String(e)));return()=>{live=false}},[page,num,query,membership,bucket,metricScope,refresh]);
 useEffect(()=>{if(detail?.detailType!=='run'||['completed','failed','cancelled','interrupted','expired'].includes(detail.state))return;let live=true;const t=setInterval(()=>api('request/'+detail.id).then(r=>{if(live)setDetail({...r,detailType:'run'})}).catch(e=>{if(live)setError(String(e))}),3000);return()=>{live=false;clearInterval(t)}},[detail?.id,detail?.state]);
 useEffect(()=>{if(page==='Insights')api('insights').then(setInsights).catch(e=>setError(String(e)))},[page,refresh]);
 function navigate(p:string){setPage(p);setNum(1);setQuery('');setMembership('');setBucket('');setMetricScope('');setDetail(null)}
 function select(c:string){setAction(c);setBatch(null);setParams(commands[c]?.default_minutes?{minutes:30,preview:false}:{});setError('')}
 async function submit(){if(submitting.current)return;submitting.current=true;setBusy(true);setError('');try{const r=await api('requests',{command:action,params,idempotency_key:(submission.current??=crypto.randomUUID()),snapshot:batch?.snapshot});setNotice('Request saved locally. Your configured desktop listener or manual SMP RUN QUEUE invocation processes it. See Runs for actual outcomes.');setAction('');navigate('Runs');setRefresh(x=>x+1);setDetail({...r,detailType:'run'});load()}catch(e){setError(String(e))}finally{submitting.current=false;setBusy(false)}}
 async function inspect(row:Row){try{if(page==='Content')setDetail({...await api('content/'+row.id),detailType:'content'});else if(page==='Network')setDetail({...await api('person/'+row.id),detailType:'person'});else if(page==='Engagement')setDetail({...await api('action/'+row.id),detailType:'engagement'});else if(page==='Opportunities')setDetail({...await api('opportunity/'+row.id),detailType:'opportunities'});else if(page==='Runs')setDetail({...await api('request/'+row.id),detailType:'run'});else setDetail({...row,detailType:page.toLowerCase()});}catch(e){setError(String(e))}}
 const cov=overview?.status.network_coverage||{}, spec=commands[action]||{};
 return <div className="app"><aside><div className="brand"><b>+</b><span>social media<span className="brandplus">plus</span></span></div><div className="workspace">YOUR WORKSPACE</div><nav>{pages.map((p,i)=><button key={p} className={page===p?'selected':''} onClick={()=>navigate(p)}><span className="navicon">{['◈','↗','▤','▧','◌','◎','▣','▥','≡','⚙'][i]}</span>{p}{p==='Runs'&&<small>{overview?.runs.filter((r:Row)=>!['completed','cancelled','failed','interrupted','expired'].includes(r.state)).length||0}</small>}</button>)}</nav><div className="sidebarfoot"><span className="avatar">+</span><div>{overview?.workspace?.owner||'Your workspace'}<small>LinkedIn · Personal profile</small></div></div></aside>
 <main><header><div><span className="eyebrow">SOCIALMEDIA+ / {page.toUpperCase()}</span><h1>{page==='Home'?'Make the next conversation count.':page}</h1><p>{({Home:'A thoughtful presence. Useful content. Relationships that last.',Actions:'Your SMP routines, in one place.',Content:'Your writing, versions and publishing evidence.',Assets:'The visuals behind your ideas.',Engagement:'Conversations and actions, with actual outcomes.',Network:'Connections and observed followers, together.',Opportunities:'Relevant roles and hiring conversations.',Insights:'Learn from what you can actually measure.',Runs:'Every request, from your click to its result.','LinkedIn setup':'Your app credentials, saved only in this local workspace.'} as Row)[page]}</p></div><button className="subtle" onClick={()=>{load();setRefresh(x=>x+1)}}>↻ Refresh</button></header>
 <div className="health"><span><i className="dot"/> Dashboard online</span><span><i className="dot"/> SQLite · local storage</span><span><i className="dot amber"/> Listener: {label(overview?.desktop?.listener?.status||'not_installed')}</span><span className="model">{overview?.desktop?.desktop_host||'Desktop host'} · selected model</span></div>
 {error&&<div role="alert" className="alert error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div role="status" className="alert">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {page==='Home'&&<><section className="platforms" aria-label="Social media platforms"><button className="platformcard active" onClick={()=>navigate('LinkedIn setup')}><span className="platformlogo">in</span><div><strong>LinkedIn</strong><small>Available · configure your apps →</small></div></button>{['Instagram','YouTube','More platforms'].map(name=><div className="platformcard coming" key={name}><span className="platformlogo">{name[0]}</span><div><strong>{name}</strong><small>Coming soon</small></div></div>)}</section><section className="hero"><div><span className="eyebrow">YOUR DAILY PRACTICE</span><h2>Show up with something<br/>worth saying.</h2><p>Start your workspace, then spend 30 minutes in relevant conversations with your network and new peers.</p><div className="buttons"><button className="primary" onClick={()=>select('START')}>Start workspace ↗</button><button onClick={()=>select('ENGAGE')}>Engage 30 minutes</button></div></div><div className="heroart" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="centerplus">+</div><span className="orbitlabel">IDEAS → CONVERSATIONS → RELATIONSHIPS</span></div></section>
 <div className="stats">{[['Content items',overview?.status.content.reduce((a:number,x:Row)=>a+x.count,0)||0,'Across all recorded states'],['Connections',cov.registered_connections??'—','Usable profile records'],['Observed followers',cov.registered_followers??'—',`${cov.registered_follower_connection_overlap??'—'} also connections`],['Needs reconciliation',overview?.status.unresolved_actions.length??'—','Check before another attempt']].map(([t,n,s])=><div className="stat" key={t}><span>{t}</span><strong>{Number.isFinite(n)?Number(n).toLocaleString():n}</strong><small>{s}</small></div>)}</div>
 <div className="columns"><section className="panel"><div className="sectionhead"><h2>Your publishing week</h2><button className="textbtn" onClick={()=>navigate('Content')}>All content →</button></div>{overview?.next_posts.map((r:Row)=><div className="listrow" key={r.id}><span className="formatmark">{r.format==='document'?'PDF':r.format==='image'?'IMG':'TXT'}</span><div><strong>{r.title}</strong><small>{date(r.scheduled_at)} · {label(r.publishing_authority)}</small></div><Badge value={r.status}/></div>)}<button className="wide" onClick={()=>select('WEEK')}>+ Prepare another week</button></section><section className="panel"><h2>Keep the routine simple</h2><div className="routine"><span>01</span><div><strong>Prepare once a week</strong><p>Performance review, ideas, drafts, assets and editorial review.</p><button className="textbtn" onClick={()=>select('WEEK')}>Prepare week →</button></div></div><div className="routine"><span>02</span><div><strong>Schedule the finished batch</strong><p>Review the exact text, assets and dates before your scheduling instruction.</p><button className="textbtn" onClick={()=>select('SCHEDULE')}>Review a batch →</button></div></div><div className="routine"><span>03</span><div><strong>Come back to conversations</strong><p>Your connections and followers share one relationship history.</p><button className="textbtn" onClick={()=>select('NETWORK')}>Your network →</button></div></div></section></div></>}
 {page==='Actions'&&<div className="actiongrid">{Object.entries(commands).map(([c,s])=><button key={c} className="actioncard" onClick={()=>select(c)}><span className="eyebrow">SMP {c}</span><h2>{names[c]||c} <span>↗</span></h2><p>{s.audience?label(s.audience):label(s.mode)}</p><small>{s.default_minutes?'30 minutes by default':c==='WEEK'?'Includes assets and review':'On your instruction'}</small></button>)}</div>}
 {!['Home','Actions','Insights','LinkedIn setup'].includes(page)&&<><div className="toolbar"><input aria-label="Search records" placeholder={'Search '+page.toLowerCase()+'…'} value={query} onChange={e=>{setQuery(e.target.value);setNum(1)}}/>{page==='Network'&&<select aria-label="Membership" value={membership} onChange={e=>{setMembership(e.target.value);setNum(1)}}><option value="">All relationships</option><option value="connection">Connections</option><option value="follower">Observed followers</option><option value="follower_only">Followers outside connections</option></select>}{page==='Network'&&<select aria-label="Professional bucket" value={bucket} onChange={e=>{setBucket(e.target.value);setNum(1)}}><option value="">All professional buckets</option>{overview?.buckets.map((b:Row)=><option key={b.bucket} value={b.bucket}>{label(b.bucket)} ({b.count})</option>)}</select>}{page==='Insights'&&<select aria-label="Metric scope" value={metricScope} onChange={e=>{setMetricScope(e.target.value);setNum(1)}}><option value="">Account and post observations</option><option value="account">Account only</option><option value="post">Individual posts</option></select>}<span>{data.total.toLocaleString()} records</span></div>
 {page==='Network'&&<div className="note">Follower coverage is based on positive observations. {cov.latest_follower_snapshot?.displayed_count?`Latest observed displayed count: ${cov.latest_follower_snapshot.displayed_count}. `:''}Missing profiles do not imply unfollows. Role buckets require current discussion context.</div>}
 {page==='Runs'&&<div className="note">Requests target your configured desktop session. Set up the host listener with runtime/install/listener-prompt.md, or send SMP RUN QUEUE in that session. Queued means not yet executed. Cancel is available before execution.</div>}
 {data.rows.length===0?<div className="empty"><h2>No {page.toLowerCase()} records here yet.</h2><p>{query?'Try another search.':'Records will appear when the corresponding workflow saves verified results.'}</p></div>:page==='Assets'?<div className="assetgrid">{data.rows.map((r:Row)=><button className="assetcard" key={r.id} onClick={()=>inspect(r)}>{r.extension==='.pdf'?<div className="pdfcover">PDF<span>Document carousel</span></div>:<img src={r.url} alt={r.alt_text}/>}<strong>{r.alt_text}</strong><small>{r.id} · {r.active?'Active':'Archived'}</small></button>)}</div>:<section className="panel tablewrap"><table><thead><tr><th>{page==='Network'?'Person':page==='Engagement'?'Action':page==='Insights'?'Measurement':page==='Runs'?'Command':'Title'}</th><th>Context</th><th>State / evidence</th><th>Last recorded</th></tr></thead><tbody>{data.rows.map((r:Row)=><tr key={r.id} onClick={()=>inspect(r)}><td><button className="rowtitle">{r.title||r.name||(page==='Runs'?'SMP '+r.command:r.metric||label(r.kind))}</button>{r.company&&<small>{r.company}</small>}{r.response&&<small className="excerpt">{r.response}</small>}</td><td>{page==='Network'?<>{r.position}<small>{r.memberships?.join(' · ')}</small></>:page==='Insights'?<>{r.value??'Unavailable'}<small>{r.scope} · {r.window}</small></>:page==='Engagement'?r.authority:page==='Runs'?`${r.model} · ${r.effort}`:r.format||r.country||r.scope}</td><td><Badge value={r.state||r.status||r.bucket||r.availability||'observed'}/></td><td>{date(r.updated_at||r.observed_at||r.created_at)}</td></tr>)}</tbody></table></section>}
 <div className="pagination"><button disabled={num===1} onClick={()=>setNum(n=>n-1)}>← Previous</button><span>Page {num} of {Math.max(1,Math.ceil(data.total/30))}</span><button disabled={num*30>=data.total} onClick={()=>setNum(n=>n+1)}>Next →</button></div></>}
 {page==='Insights'&&<Insights data={insights}/>}
 {page==='LinkedIn setup'&&<LinkedInSettings status={overview?.linkedin} save={async body=>{const result=await api('settings/linkedin',body);await load();return result}}/>}
 <footer>Private workspace · {overview?.workspace?.timezone||'UTC'} · Last refreshed {overview?date(overview.observed_at):'…'}</footer></main>
 {action&&<div className="overlay"><section role="dialog" aria-modal="true" aria-label={names[action]} className="modal"><button className="close" onClick={()=>setAction('')}>×</button><span className="eyebrow">SMP {action}</span><h2>{names[action]}</h2>{error&&<div role="alert" className="alert error">{error}</div>}<p>{spec.authorization||label(spec.mode)}</p><div className="note">This saves a local request for your desktop session. It runs when that session processes the queue.</div>
 {spec.default_minutes&&<><label>Session length<select value={params.minutes} onChange={e=>setParams({...params,minutes:Number(e.target.value)})}>{[15,30,45,60,90,120].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label>{action==='NETWORK'&&<label>Audience<select onChange={e=>setParams({...params,audience:e.target.value})}><option value="">Connections and followers</option><option value="followers">Followers</option><option value="connections">Connections</option></select></label>}<label className="check"><input type="checkbox" checked={params.preview} onChange={e=>setParams({...params,preview:e.target.checked})}/> Preview only (optional)</label></>}
 {['WEEK','REVIEW','SCHEDULE','REWORK'].includes(action)&&<label>Week starting Monday<input type="date" value={params.week||''} onChange={e=>{setParams({...params,week:e.target.value,content_id:''});setBatch(null)}}/></label>}
 {['ASSET','REWORK','SCHEDULE'].includes(action)&&<label>Or content ID<input value={params.content_id||''} placeholder="Select a content ID from Content" onChange={e=>{setParams({...params,content_id:e.target.value,week:''});setBatch(null)}}/></label>}
 {['REWORK','ASSET'].includes(action)&&<label>Your brief<textarea maxLength={4000} onChange={e=>setParams({...params,brief:e.target.value})}/></label>}
 {action==='IMPORT'&&<label>LinkedIn export<input type="file" accept=".zip,.csv,.xlsx" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);try{const r=await fetch('/api/upload?extension='+f.name.split('.').pop(),{method:'POST',headers:{'X-SMP-Token':token},body:f});const d=await r.json();if(!r.ok)throw Error(d.error);setParams({file:d.file});setNotice('Export saved locally for the import request.')}catch(e){setError(String(e))}finally{setBusy(false)}}}/></label>}
 {action==='SCHEDULE'&&<><button onClick={async()=>{try{setBatch(await api('snapshot?'+new URLSearchParams(params as Record<string,string>)))}catch(e){setError(String(e))}}}>Load exact batch for review</button>{batch?.items.map((r:Row)=><article className="batchitem" key={r.id}><h3>{r.title}</h3><p>{date(r.scheduled_at)} · {label(r.authority)} · Version {r.version}</p><pre>{r.text}</pre>{r.assets.map((a:Row)=><a key={a.id} href={'/api/asset/'+a.id} target="_blank" rel="noreferrer">View asset: {a.alt_text} ↗</a>)}</article>)}</>}
 <div className="buttons"><button className="primary" disabled={busy||(action==='SCHEDULE'&&!batch)} onClick={submit}>{busy?'Saving…':action==='SCHEDULE'?'Save scheduling instruction':'Save request'}</button><button onClick={()=>setAction('')}>Cancel</button></div></section></div>}
 {detail&&<div className="overlay"><section role="dialog" aria-modal="true" aria-label="Record details" className="modal"><button className="close" onClick={()=>setDetail(null)}>×</button><span className="eyebrow">{detail.id}</span><h2>{detail.title||detail.name||(detail.command?'SMP '+detail.command:label(detail.kind||detail.metric||'Asset'))}</h2><Badge value={detail.state||detail.status||detail.bucket||detail.availability||'registered'}/>{detail.text&&<pre>{detail.text}</pre>}{detail.response&&<pre>{detail.response}</pre>}
 {detail.detailType==='run'&&<><p>{detail.result||'Saved, awaiting verified Desktop dispatch.'}</p><p>{detail.model} · {detail.effort}</p><p>Latest permitted start: {date(detail.expires_at)}. An expired request requires a new invocation.</p><button onClick={async()=>{try{await navigator.clipboard.writeText(detail.prompt);setNotice('Command copied. In your configured desktop session, use SMP RUN QUEUE to process the saved request and record its outcome.')}catch{setError('Clipboard unavailable. Select the command text below.')}}}>Copy saved instruction</button><pre>{detail.prompt}</pre>{['queued','waiting'].includes(detail.state)&&<button onClick={async()=>{try{setDetail({...await api('cancel/'+detail.id,{}),detailType:'run'});setRefresh(x=>x+1);load()}catch(e){setError(String(e))}}}>Cancel queued request</button>}<h3>Timeline</h3>{detail.events?.map((e:Row)=><div className="event" key={e.sequence}><Badge value={e.type}/><p>{e.detail}</p><small>{date(e.created_at)}</small></div>)}</>}
 {detail.detailType==='assets'&&<>{detail.extension==='.pdf'?<iframe title="PDF preview" src={detail.url}/>:<img className="preview" src={detail.url} alt={detail.alt_text}/>}<p>{detail.alt_text}</p><a href={detail.url} target="_blank" rel="noreferrer">Open asset ↗</a></>}
 {detail.profile_url&&<p><Link url={detail.profile_url}>LinkedIn profile</Link></p>}{detail.target_url&&<p><Link url={detail.target_url}>View original discussion</Link></p>}{detail.job_url&&<p><Link url={detail.job_url}>View job</Link></p>}
 {detail.bucket_evidence&&<p>{detail.bucket_evidence}</p>}{detail.topic&&<p>{detail.topic}</p>}{detail.position&&<p>{detail.position} · {detail.company}</p>}
 {detail.assets?.map((a:Row)=><p key={a.id}><a href={'/api/asset/'+a.id} target="_blank" rel="noreferrer">Asset: {a.alt_text}{a.active===0?' (archived version)':''} ↗</a></p>)}
 {detail.actions?.map((a:Row)=><div className="event" key={a.id}><Badge value={a.state}/><p>{label(a.kind)} · {date(a.updated_at)}</p><Link url={a.remote_url}>External receipt</Link></div>)}
 {detail.interactions?.map((i:Row)=><div className="event" key={i.id}><Badge value={i.state}/><pre>{i.response}</pre><Link url={i.target_url}>Conversation</Link></div>)}
 {detail.detailType==='insights'&&<><h3>{detail.value??'Unavailable'}</h3><p>{detail.scope} · {detail.window} · {date(detail.observed_at)}</p><p>Source: {detail.source}</p></>}
 {detail.receipts?.map((r:Row)=><div className="event" key={r.id}><Badge value={r.state}/><p>{r.evidence}</p><small>{date(r.observed_at)}</small><Link url={r.remote_url}>External result</Link></div>)}
 {detail.evidence&&<><h3>Observed job evidence</h3><pre>{JSON.stringify(detail.evidence,null,2)}</pre></>}
 {detail.metrics&&<><h3>Measurements</h3>{detail.metrics.length?detail.metrics.map((m:Row)=><p key={m.id}>{m.metric}: {m.value??'Unavailable'} · {m.window} · {date(m.observed_at)}</p>):<p>No measurements recorded for this post yet.</p>}</>}
 </section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
